### ISSUE TITLE
Working with two different PWM frequency ?

### ISSUE THREAD

**Issue by ServeurpersoCom** [xinkaiwang/rpio-pwm#1]
Hello,

I need to drive Servo - 20ms standard repeat time - and H-Bridge with faster repeat time (3000 uS)

I tested with two (unused) different DMA channel but the slower PWM (servo) go wrong.

I also tested to use the hardware PWM library "raspi-pwm" but the DMA PWM "rpio-pwm" stop working after writing to HPWM I/O.

Any idea ?

**Comment by xinkaiwang** [comment]
Due to those 2 application require 2 different cycle time, I believe you will just need to use 2 different DMA channels for those 2 applications. I use channel 14 in my demo, you may need to do some homework to find out another un-used channel for you to use.

**Comment by xinkaiwang** [comment]
@Serveurperso , you may want to try my newest update 1.0.x which added support for the mode you need. And you may also want to check my other project perf-gpio, where you can find sample code on how to setup 2 channel to do those things at the same time.
