### ISSUE TITLE
Debian buster need #include <sys/sysmacros.h> inside pwm.c

### ISSUE THREAD

**Issue by ServeurpersoCom** [xinkaiwang/rpio-pwm#3]
Debian buster need #include <sys/sysmacros.h> inside pwm.c

Tested on Raspberry PI 3 B+

Warning Raspberry PI 4 need a ServoBlaster Broadcom register/low level code update else it segfault and crash sshd !!!!!

**Comment by xinkaiwang** [comment]
just fixed the <sys/sysmacros.h>

**Comment by xinkaiwang** [comment]
I just tried it on pi4, you are right, it do corrupts kernel. Do you have any quick fix? @Serveurperso

**Comment by ServeurpersoCom** [comment]
Sorry, now I use "pigpio" on my robot community project (vigibot.com)

**Comment by xinkaiwang** [comment]
This problem is fully fixed by 1.0.0. I re-write the whole thing, and now it supports Pi4 as well.
